### ISSUE TITLE
Хуйня с хакари

### ISSUE THREAD

**Issue by hikariatama** [error4ikLOH/modules_frendly_telegram#1]
Pretending to be author of snippet, even if he's not.
https://github.com/hikariatama/host/blob/master/lovemagic.py
(I don't pretend to be author either, but nonetheless, I don't tell, that "I'm the author of this module")

**Comment by hikariatama** [comment]
Lol, just noticed, that till https://github.com/error4ikLOH/modules_frendly_telegram/commit/318bb6baa5f668efcfde4fbc1571e0cf54842ed3 it was literally the copy of original module

**Comment by error4ikLOH** [comment]
Абоба
